# Generated by Django 5.1 on 2024-09-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioactiveMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('constant', models.FloatField(db_index=True, help_text='em mSv.m2/h.GBq')),
            ],
        ),
    ]
